language: java
jdk:
  - openjdk8
deploy:
  provider: heroku
  api_key:
    secure: X4WmE5JmcH8yOd1EfJtYyTSpZNI6aGxiiSVJ8hfJzZROLPj8M3ldCRiUz1r7+pJ4v7Kq3jXols/BXnT1HtnKYYpZggJrDu5UlbxZfTxfzCfFV3q+Y6Yp7OAOGloSYNeUYqt9mZnAfDbuS19rT12w0dDQypBau2O7JFKMOun01isM2eZargGoW9G+eEBMC82sjJFa7ZuqaPkvdG1hFDX0W4YW1V1G8PDRcb8g1OfTUc7KnoMy9TpepO7XZRD0wTcCkY+uqxvhgyVduGIEdH6OZrGsw8TaZi4DIalnyJ6eMaVvOU6pEgGu5jHOOTDli4GvnI+TFqslXVMCMPRZhcqSSfMPAVru4ApYbsnRSiTwZGpT6kEU2MysOr4hzjeDfRDHRb8EBus9CPR0EFGlPcXgeJg21Gp171W9i/MFqyvU4aypWdlAuYTSRyDYbSYFieHf1Qhn6EXHHpTeHI3753cs6yctaxZsO8zbZ7Or3g2QyJHDc5Rbt7muTVA5D544+ZqdvJpLXo/pmtEyPjlZjD03tcglTjVXJbqbiNvBByb10mq5iJTUITYkdaPMZg/E6LfS2gxBwhSEGt/2D/uyZ/lcJfxDm5U3OMOCLUzSBohBqHxoRjV9SKOP/WX3Cr3hVQXZs+T7Kj+rPcLrhPtr2Oc4KzuKTvXhCGmbpTZcwu5EKbA=
  app: globalradio2
  on:
    repo: alakijaayo/globalradio1